apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: loghmeh-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loghmeh
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loghmeh
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            # - name: MYSQL_ROOT_PASSWORD
            #   valueFrom:                # Read environment variables from kubernetes secrets
            #     secretKeyRef:
            #       name: mysql-root-pass
            #       key: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: loghmeh
          resources:
            requests:
              memory: 500Mi
              cpu: 400m
            limits:
              memory: 600Mi
              cpu: 600m
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
            - --skip-character-set-client-handshake
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
      memory: 500Mi
      cpu: 400m
    limits:
      memory: 600Mi
      cpu: 600m