apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          .: {}
          k:{"port":3306,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: oc
    operation: Update
    time: 2020-06-11T07:06:56Z
  name: loghmeh-mysql
  selfLink: /api/v1/namespaces/baharan-aylin-ns/services/loghmeh-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: loghmeh
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
