stages:
  - build
  - deliver

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE_DOCKERHUB" .
  after_script:
    - docker save -o ${CI_PROJECT_NAME}.tar "$CI_REGISTRY_IMAGE_DOCKERHUB"

deliver:
  image: docker:latest
  services:
    - docker:dind
  stage: deliver
  dependencies:
    - build
  before_script:
    - docker login -u "$CI_REGISTRY_USER_DOCKERHUB" -p "$CI_REGISTRY_PASSWORD_DOCKERHUB" $CI_REGISTRY_DOCKERHUB
    - docker load --input ${CI_PROJECT_NAME}.tar
    - docker tag ${CI_PROJECT_NAME} "$CI_REGISTRY_IMAGE_DOCKERHUB"
  script:
    - docker push "$CI_REGISTRY_IMAGE_DOCKERHUB"
