# This file is a template, and might need editing before it works on your project.
# Official docker image.
stages:
  - build
  - deliver

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE_DOCKERHUB" .

deliver:
  image: docker:latest
  services:
    - docker:dind
  stage: deliver
  before_script:
    - docker login -u "$CI_REGISTRY_USER_DOCKERHUB" -p "$CI_REGISTRY_PASSWORD_DOCKERHUB" $CI_REGISTRY_DOCKERHUB
  script:
    - docker push "$CI_REGISTRY_IMAGE_DOCKERHUB"
